# docker-compose.yml
services:
  postgres:
    image: postgres:15-alpine
    container_name: todo_postgres
    environment:
      POSTGRES_DB: todo_cli
      POSTGRES_USER: todo_user
      POSTGRES_PASSWORD: todo_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U todo_user -d todo_cli" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # Optional: Database admin UI
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: todo_pgadmin
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@todo.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"

volumes:
  postgres_data:
